# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate the log-likelihood under the hybrid process
#'
#' @param par vector of length 3, containing (in that order) the power parameter lambda, the exponent parameter theta, and the scale parameter.
#' @param x vector of cumulative/absolute event times.
#' @export
llik_nhpp_hybrid <- function(par, x) {
    .Call('_hybridProcess_llik_nhpp_hybrid', PACKAGE = 'hybridProcess', par, x)
}

#' Evaluate the log-likelihood under a special case of hybrid process when the power parameter is 0
#'
#' @param par vector of length 2, containing (in that order) the exponent parameter theta, and the scale parameter.
#' @param x vector of cumulative/absolute event times.
#' @export
llik_nhpp_exp <- function(par, x) {
    .Call('_hybridProcess_llik_nhpp_exp', PACKAGE = 'hybridProcess', par, x)
}

#' Evaluate the log-likelihood under the power law process, equivalently a special case of hybrid process when the exponent parameter is 0
#'
#' @param par vector of length 2, containing (in that order) the power parameter lambda, and the scale parameter.
#' @param x vector of cumulative/absolute event times.
#' @export
llik_nhpp_power <- function(par, x) {
    .Call('_hybridProcess_llik_nhpp_power', PACKAGE = 'hybridProcess', par, x)
}

llik_etas <- function(beta, kappa, lambda, phi, psi, theta, x, e, t_original, m_retweets, t_relative, t_infinity) {
    .Call('_hybridProcess_llik_etas', PACKAGE = 'hybridProcess', beta, kappa, lambda, phi, psi, theta, x, e, t_original, m_retweets, t_relative, t_infinity)
}

#' Run the Metropolis-within-Gibbs algorithm for the hierarchical model of hybrid processes
#'
#' @param beta,kappa,lambda,phi,psi,tau,theta initial values of the parameters.
#' @param x,t_original,m_retweets,t_relative numeric vectors of follower counts, creation times of original tweets, number of retweets, and times of retweets relative to their corresponding original tweets.
#' @param t_infinity numeric scalar, duration of data collection.
#' @param s_beta,s_kappa,s_lambda,s_psi,s_theta,s_e_init initial values of proposal standard deviations.
#' @param N desired chain length AFTER burn-in and thinning.
#' @param thin thinning in MCMC.
#' @param burnin burn-in in MCMC.
#' @param print_freq how frequent should the current values in the MCMC be printed.
#' @param a_theta_prop shape parameter of pseudoprior for theta.
#' @param b_theta_prop rate parameter of pseudoprior for theta.
#' @param p0 prior for power-law process as opposed to hybrid process.
#' @param p01 jump probability from model 0 to 1 in RJMCMC.
#' @param p10 jump probability from model 1 to 0 in RJMCMC.
#' @param write boolean; should csv files of estimated and predicted retweet counts be written?
#' @param filename_par,filename_m,filename_p names of the csv files for the chains of the parameters, the estimated retweet counts and the predicted retweet counts, respectively; ignored if write is FALSE.
#' @param mu_beta,tau_beta,mu_kappa,tau_kappa,a_lambda,b_lambda,a_phi,b_phi,a_psi,b_psi,a_tau,b_tau,a_theta,b_theta hyperparameters for the priors of beta, kappa, lambda, phi, psi, tau, and theta, respectively.
#' @export
mh_etas <- function(beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par = "default_par.csv", filename_m = "default_m.csv", filename_p = "default_p.csv", mu_beta = 0.0, tau_beta = 1.0e-4, mu_kappa = 0.0, tau_kappa = 1.0e-4, a_lambda = 1.0, b_lambda = 1.0e-3, a_phi = 1.0, b_phi = 1.0e-3, a_psi = 1.0, b_psi = 1.0e-3, a_tau = 1.0, b_tau = 1.0e-3, a_theta = 1.0, b_theta = 1.0e-3) {
    .Call('_hybridProcess_mh_etas', PACKAGE = 'hybridProcess', beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par, filename_m, filename_p, mu_beta, tau_beta, mu_kappa, tau_kappa, a_lambda, b_lambda, a_phi, b_phi, a_psi, b_psi, a_tau, b_tau, a_theta, b_theta)
}

#' Run the Reversible-jump MCMC algorithm for the hierarchical model of hybrid processes
#'
#' @param beta,kappa,lambda,phi,psi,tau,theta initial values of the parameters.
#' @param x,t_original,m_retweets,t_relative numeric vectors of follower counts, creation times of original tweets, number of retweets, and times of retweets relative to their corresponding original tweets.
#' @param t_infinity numeric scalar, duration of data collection.
#' @param s_beta,s_kappa,s_lambda,s_psi,s_theta,s_e_init initial values of proposal standard deviations.
#' @param N desired chain length AFTER burn-in and thinning.
#' @param thin thinning in MCMC.
#' @param burnin burn-in in MCMC.
#' @param print_freq how frequent should the current values in the MCMC be printed.
#' @param a_theta_prop shape parameter of pseudoprior for theta.
#' @param b_theta_prop rate parameter of pseudoprior for theta.
#' @param p0 prior for power-law process as opposed to hybrid process.
#' @param p01 jump probability from model 0 to 1 in RJMCMC.
#' @param p10 jump probability from model 1 to 0 in RJMCMC.
#' @param write boolean; should csv files of estimated and predicted retweet counts be written?
#' @param filename_par,filename_m,filename_p names of the csv files for the chains of the parameters, the estimated retweet counts and the predicted retweet counts, respectively; ignored if write is FALSE.
#' @param mu_beta,tau_beta,mu_kappa,tau_kappa,a_lambda,b_lambda,a_phi,b_phi,a_psi,b_psi,a_tau,b_tau,a_theta,b_theta hyperparameters for the priors of beta, kappa, lambda, phi, psi, tau, and theta, respectively.
#' @export
rj_etas <- function(beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par = "default_par.csv", filename_m = "default_m.csv", filename_p = "default_p.csv", mu_beta = 0.0, tau_beta = 1.0e-4, mu_kappa = 0.0, tau_kappa = 1.0e-4, a_lambda = 1.0, b_lambda = 1.0e-3, a_phi = 1.0, b_phi = 1.0e-3, a_psi = 1.0, b_psi = 1.0e-3, a_tau = 1.0, b_tau = 1.0e-3, a_theta = 1.0, b_theta = 1.0e-3) {
    .Call('_hybridProcess_rj_etas', PACKAGE = 'hybridProcess', beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par, filename_m, filename_p, mu_beta, tau_beta, mu_kappa, tau_kappa, a_lambda, b_lambda, a_phi, b_phi, a_psi, b_psi, a_tau, b_tau, a_theta, b_theta)
}

#' Run the Gibbs variable selection algorithm for the hierarchical model of hybrid processes
#'
#' @param beta,kappa,lambda,phi,psi,tau,theta initial values of the parameters.
#' @param x,t_original,m_retweets,t_relative numeric vectors of follower counts, creation times of original tweets, number of retweets, and times of retweets relative to their corresponding original tweets.
#' @param t_infinity numeric scalar, duration of data collection.
#' @param s_beta,s_kappa,s_lambda,s_psi,s_theta,s_e_init initial values of proposal standard deviations.
#' @param N desired chain length AFTER burn-in and thinning.
#' @param thin thinning in MCMC.
#' @param burnin burn-in in MCMC.
#' @param print_freq how frequent should the current values in the MCMC be printed.
#' @param a_theta_prop shape parameter of pseudoprior for theta.
#' @param b_theta_prop rate parameter of pseudoprior for theta.
#' @param p0 prior for power-law process as opposed to hybrid process.
#' @param p01 jump probability from model 0 to 1 in RJMCMC.
#' @param p10 jump probability from model 1 to 0 in RJMCMC.
#' @param write boolean; should csv files of estimated and predicted retweet counts be written?
#' @param filename_par,filename_m,filename_p names of the csv files for the chains of the parameters, the estimated retweet counts and the predicted retweet counts, respectively; ignored if write is FALSE.
#' @param mu_beta,tau_beta,mu_kappa,tau_kappa,a_lambda,b_lambda,a_phi,b_phi,a_psi,b_psi,a_tau,b_tau,a_theta,b_theta hyperparameters for the priors of beta, kappa, lambda, phi, psi, tau, and theta, respectively.
#' @export
ms_etas <- function(beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par = "default_par.csv", filename_m = "default_m.csv", filename_p = "default_p.csv", mu_beta = 0.0, tau_beta = 1.0e-4, mu_kappa = 0.0, tau_kappa = 1.0e-4, a_lambda = 1.0, b_lambda = 1.0e-3, a_phi = 1.0, b_phi = 1.0e-3, a_psi = 1.0, b_psi = 1.0e-3, a_tau = 1.0, b_tau = 1.0e-3, a_theta = 1.0, b_theta = 1.0e-3) {
    .Call('_hybridProcess_ms_etas', PACKAGE = 'hybridProcess', beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par, filename_m, filename_p, mu_beta, tau_beta, mu_kappa, tau_kappa, a_lambda, b_lambda, a_phi, b_phi, a_psi, b_psi, a_tau, b_tau, a_theta, b_theta)
}

#' Run the Metropolised Gibbs variable selection algorithm for the hierarchical model of hybrid processes
#'
#' @param beta,kappa,lambda,phi,psi,tau,theta initial values of the parameters.
#' @param x,t_original,m_retweets,t_relative numeric vectors of follower counts, creation times of original tweets, number of retweets, and times of retweets relative to their corresponding original tweets.
#' @param t_infinity numeric scalar, duration of data collection.
#' @param s_beta,s_kappa,s_lambda,s_psi,s_theta,s_e_init initial values of proposal standard deviations.
#' @param N desired chain length AFTER burn-in and thinning.
#' @param thin thinning in MCMC.
#' @param burnin burn-in in MCMC.
#' @param print_freq how frequent should the current values in the MCMC be printed.
#' @param a_theta_prop shape parameter of pseudoprior for theta.
#' @param b_theta_prop rate parameter of pseudoprior for theta.
#' @param p0 prior for power-law process as opposed to hybrid process.
#' @param p01 jump probability from model 0 to 1 in RJMCMC.
#' @param p10 jump probability from model 1 to 0 in RJMCMC.
#' @param write boolean; should csv files of estimated and predicted retweet counts be written?
#' @param filename_par,filename_m,filename_p names of the csv files for the chains of the parameters, the estimated retweet counts and the predicted retweet counts, respectively; ignored if write is FALSE.
#' @param mu_beta,tau_beta,mu_kappa,tau_kappa,a_lambda,b_lambda,a_phi,b_phi,a_psi,b_psi,a_tau,b_tau,a_theta,b_theta hyperparameters for the priors of beta, kappa, lambda, phi, psi, tau, and theta, respectively.
#' @export
me_etas <- function(beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par = "default_par.csv", filename_m = "default_m.csv", filename_p = "default_p.csv", mu_beta = 0.0, tau_beta = 1.0e-4, mu_kappa = 0.0, tau_kappa = 1.0e-4, a_lambda = 1.0, b_lambda = 1.0e-3, a_phi = 1.0, b_phi = 1.0e-3, a_psi = 1.0, b_psi = 1.0e-3, a_tau = 1.0, b_tau = 1.0e-3, a_theta = 1.0, b_theta = 1.0e-3) {
    .Call('_hybridProcess_me_etas', PACKAGE = 'hybridProcess', beta, kappa, lambda, phi, psi, tau, theta, x, t_original, m_retweets, t_relative, t_infinity, s_beta, s_kappa, s_lambda, s_psi, s_theta, s_e_init, N, thin, burnin, print_freq, a_theta_prop, b_theta_prop, p0, p01, p10, write, filename_par, filename_m, filename_p, mu_beta, tau_beta, mu_kappa, tau_kappa, a_lambda, b_lambda, a_phi, b_phi, a_psi, b_psi, a_tau, b_tau, a_theta, b_theta)
}

